/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\Hair.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF(`${import.meta.env.VITE_API_URL}/fileinfo/1683528029682Hair.glb`)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Hair.geometry} material={materials.Hair} material-color={props.bodyColor} />
    </group>
  )
}

useGLTF.preload('/Hair.glb')
